### PR TITLE
Awesome books: with ES6

### PR DESCRIPTION
**Pull request by joffreynk**
### Awesome books: with ES6

- Created a new directory and initialize it with git.
- Used npm init -y command to create package.json file.
- Created the entry point for JavaScript code called index.js
- Created index.css file for your styles.
- Created the main index.html file and Linked index.js and index.css files there.
- Created a directory called modules.
- used a library Luxon

luxon produces many errors

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @JoffreyNK, please fix linter errors on this pull request, if not your project will be invalidated because it does not pass the ESlint linter check 👍🏿

**Review by prolajumokeoni — COMMENTED** [review]
Hi @JoffreyNK,  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project,  that does not pass the ESlint linter check 👍🏿

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by joffreynk** [comment]
Hi, I cannot fix luxon.js errors unless I get help. It's a library we are using
fixing it is really hard

**Review by Wes-Isaac — APPROVED** [review]
Hi @JoffreyNK, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Linters are all green ✔️.
- Project works as expected 🚀.
- README looks professional 😮.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
